[package]
name = "next-gen-signing-service"
version = "0.0.1"
edition = "2021"

[dependencies]
next-gen-signatures = { path = "../next-gen-signatures", features = [
    "all-algos",
] }
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.210"
