[package]
name = "next-gen-signatures"
version = "0.0.3"
edition = "2021"

[features]
all-algos = ["fips204", "bbs"]
fips204 = ["dep:fips204"]
bbs = [
    "dep:ark-bls12-381",
    "dep:ark-ec",
    "dep:ark-serialize",
    "dep:bbs_plus",
    "dep:blake2",
    "dep:num-bigint",
    "dep:rand",
]

[dependencies]
anyhow = "1.0.89"
base64 = "0.22.1"
paste = "1.0.15"
rocket = "0.5.1"

# FIPS204
fips204 = { version = "0.2.2", optional = true }

# BBS+
ark-bls12-381 = { version = "0.4.0", optional = true }
ark-ec = { version = "0.4.2", optional = true }
ark-serialize = { version = "0.4.2", optional = true }
bbs_plus = { version = "0.22.0", optional = true }
blake2 = { version = "0.10.6", optional = true }
num-bigint = { version = "0.4.6", optional = true }
rand = { version = "0.8.5", optional = true }
ark-std = "0.4.0"
dock_crypto_utils = "0.20.0"
schnorr_pok = "0.20.0"
