name: Build and Deploy (Dev)
'on':
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      repo_branch:
        description: Repo branch
        type: string
        required: true
        default: main
run-name: 'Deploy ${{ inputs.repo_branch || github.ref_name }} (Dev)'
jobs:
  create-docker-image:
    name: Create Docker Image
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build and push docker image
        uses: UbiqueInnovation/action-systems-docker-build-and-push@v1.0.0
        with:
          image_name: next-gen-signing-service-dev
          registry: ${{ secrets.UBIQUE_ACR_REGISTRY }}
          username: ${{ secrets.UBIQUE_ACR_USERNAME }}
          password: ${{ secrets.UBIQUE_ACR_PASSWORD }}
  deploy:
    name: Deploy Dev Webserver
    uses: UbiqueInnovation/workflows-backend/.github/workflows/k8s_deploy.yml@main
    needs:
      - create-docker-image
    with:
      ref_name: '${{ inputs.repo_branch || github.ref_name }}'
      tag_add_commithash: true
      namespace: sprind-eudi
      app_name: next-gen-signing-service-dev
      app_directory: .
      target: dev
      with_configmap: false
    secrets:
      acr_registry: '${{ secrets.UBIQUE_ACR_REGISTRY }}'
      acr_username: '${{ secrets.UBIQUE_ACR_USERNAME }}'
      acr_password: '${{ secrets.UBIQUE_ACR_PASSWORD }}'
      az_client_id: '${{ secrets.AZ_UB_CLIENT_ID }}'
      az_tenant_id: '${{ secrets.AZ_UB_TENANT_ID }}'
      az_subscription_id: '${{ secrets.AZ_UB_SUBSCRIPTION_ID }}'
