name: 'Rust Checks: rustfml, clippy & test'
on:
  pull_request: null
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check clippy
        uses: UbiqueInnovation/action-systems-rust-clippy@main
      - name: Check formatting
        uses: UbiqueInnovation/action-systems-rust-format@main
      - name: Run and report tests
        uses: UbiqueInnovation/action-systems-rust-test@main
