name: 'Rust Checks: rustfml, clippy & test'
on:
  pull_request: null
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: UbiqueInnovation/action-systems-rust-clippy@v1.0.0
      - uses: UbiqueInnovation/action-systems-rust-format@v1.0.0
      - uses: UbiqueInnovation/action-systems-rust-test@v1.0.0
